temas = {
        "Professor / Conteúdo": [
            "professor", "coordenador", "explica", "didatica", "postura", "aula", "aulas", "avaliação"
            "ensino", "paciencia", "atencioso", "materia", "material", "grade", "aprendizado", 
            "instrutor", "docente", "educador", "orientador", "mentor", "explicação", "explicações", "explicou", "explicando", "ensina", "ensinou", "ensinar", "didático", "didática", "didatico", "didatica", "metodologia", "metodo", "metodico", "metodica", "clareza", "claro", "objetivo", "objetiva", "confuso", "confusa", "confusão", "postura", "atitude", "atenção", "atencioso", "atenciosa", "paciente", "impaciente", "dedicado", "dedicada", "desinteressado", "desinteressada"
            "ler", "apostila", "slides", "pdf", "leitura", "livro", "prova", "exercicio","conteudo", "assunto", "tema", "topico", "assunto", "dificil de entender", "dificil de aprender", "dificil de acompanhar", "dificil de seguir", "dificil de compreender", "dificil de assimilar", "dificil de captar", "dificil de absorver", "dificil de pegar", "dificil de entender", "dificil de aprender", "dificil de acompanhar", "dificil de seguir", "dificil de compreender", "dificil de assimilar", "dificil de captar", "dificil de absorver", "dificil de pegar","dificil de entender", "dificil de aprender", "dificil de acompanhar", "dificil de seguir", "dificil de compreender", "dificil de assimilar", "dificil de captar", "dificil de absorver", "dificil de pegar", "facil de entender", "facil de aprender", "facil de acompanhar", "facil de seguir", "facil de compreender", "facil de assimilar", "facil de captar", "facil de absorver", "facil de pegar"],
        
        "Elogio": [
            "gostei", "amei", "excelente", "otimo", "perfeito", "parabens", "interessante", "Excelente", "ótimo", "perfeito", "parabéns", "interessante","muito bom", "super recomendo","recomendo", "satisfeito", "satisfacao", "satisfaz", "satisfazendo", "satisfez", "satisfeito", "satisfeitos", "satisfeita", "satisfeitas","gostei", "amei", "excelente", "otimo", "perfeito", "parabens", "interessante",   
            "motivador", "divertido", "top", "bom", "show","maravilhoso", "incrivel", "fantastico", "adorei", "muito bom", "super recomendo","parabéns","recomendo", "satisfeito", "satisfacao", "satisfaz", "satisfazendo", "satisfez", "satisfeito", "satisfeitos", "satisfeita", "satisfeitas",
            "tudo 100%", "tudo 100", "tudo 10", "tudo 10%", "tudo dez", "tudo dez por cento", "nota 10", "nota 10%", "nota dez", "nota dez por cento", "perfeito", "perfeita", "perfeitos", "perfeitas","gostei", "amei", "excelente", "otimo", "perfeito", "parabens", "interessante",   
            "motivador", "divertido", "top", "bom", "show","maravilhoso", "incrivel", "fantastico", "adorei", "muito bom", "super recomendo","parabéns","recomendo", "satisfeito", "satisfacao", "satisfaz", "satisfazendo", "satisfez", "satisfeito", "satisfeitos", "satisfeita", "satisfeitas",
            "Fácil entendimento", "Fácil de entender", "Fácil de aprender", "Fácil de acompanhar", "Fácil de seguir", "Fácil de compreender", "Fácil de assimilar", "Fácil de captar", "Fácil de absorver", "Fácil de pegar","fácil entendimento", "fácil de entender", "fácil de aprender", "fácil de acompanhar", "fácil de seguir", "fácil de compreender", "fácil de assimilar", "fácil de captar", "fácil de absorver", "fácil de pegar"
            "muito boa","boa","explicativa", "didatica", "didatico", "didatica", "didática", "didático", "didática", "didático", "didatica", "didático", "didática", "didático","professor excelente", "professor ótimo", "professor perfeito", "professor parabéns", "professor interessante","professor muito bom", "professor super recomendo","professor recomendo", "professor satisfeito", "professor satisfacao", "professor satisfaz", "professor satisfazendo", "professor satisfez", "professor satisfeito", "professor satisfeitos", "professor satisfeita", "professor satisfeitas",
            "proveitoso", "proveitosa", "proveitosos", "proveitosas", "útil", "úteis", "valioso", "valiosa", "valiosos", "valiosas"
            "satisfeito", "satisfacao", "satisfaz", "satisfazendo", "satisfez", "satisfeito", "satisfeitos", "satisfeita", "satisfeitas","gostei", "amei", "excelente", "otimo", "perfeito", "parabens", "interessante",
            "apaixonado", "apaixonada", "apaixonados", "apaixonadas", "encantado", "encantada", "encantados", "encantadas", "maravilhado", "maravilhada", "maravilhados", "maravilhadas","maravilhoso", "incrivel", "fantastico", "adorei", "muito bom", "super recomendo","parabéns","recomendo", "satisfeito", "satisfacao", "satisfaz", "satisfazendo", "satisfez", "satisfeito", "satisfeitos", "satisfeita", "satisfeitas"
            "boa abordagem", "abordagem boa", "abordagem excelente", "abordagem ótima", "abordagem perfeita", "abordagem parabéns", "abordagem interessante","abordagem muito boa", "abordagem super recomendo","abordagem recomendo", "abordagem satisfeito", "abordagem satisfacao", "abordagem satisfaz", "abordagem satisfazendo", "abordagem satisfez", "abordagem satisfeito", "abordagem satisfeitos", "abordagem satisfeita", "abordagem satisfeitas",   
            ],
        
        "Erro - BUG": [
            "travou", "acesso", "bug", "estabilidade", "app", "aplicativo", "link", 
            "moodle", "blackboard", "lag", "conexao", "lentidao", "carregamento", "erro","falha", "instabilidade", "problema tecnico", "problema de acesso", "problema de conexao", "problema de carregamento", "problema de link", "problema de app", "problema de aplicativo", "travamento", "travou", "lag", "lentidao","problema tecnico", "problema de acesso", "problema de conexao", "problema de carregamento", "problema de link", "problema de app", "problema de aplicativo",
            "erro", "falha", "bug", "travou", "travamento", "instabilidade", "problema tecnico", "problema técnico", "problema de sistema", "problema no sistema", "problema de plataforma", "problema de site", "problema de servidor", "problema de login", "problema de senha", "problema de cadastro", "problema de acesso", "problema de conexão", "problema de internet", "problema de carregamento", "problema de link", "problema de app", "problema de aplicativo", "problema de programa", "problema de software", "problema de hardware"
            ],
        
        "Audio": [
          "audio", "som", "ruido", "chiado", "mudo", "baixo", "alto", "volume baixo", "volume alto", "volume ruim", "volume péssimo", "volume fraco", "volume forte", "sem som", "sem áudio", "não tem som", "não tem áudio", "não sai som", "não sai áudio", "não escuto", "não ouço", "não consigo ouvir", "não consigo escutar", "não consigo entender", "dificil de ouvir", "dificil de escutar", "dificil de entender", "dificil de compreender",
          "microfone", "mic", "voz", "fala", "falando", "falar", "voz baixa", "voz alta", "voz ruim", "voz péssima", "voz fraca", "voz forte", "voz clara", "voz confusa", "voz distante", "voz próxima", "voz cortada", "voz falhando", "voz travando",
          "qualidade do som", "qualidade do áudio", "qualidade ruim", "qualidade péssima", "qualidade baixa", "qualidade fraca", "qualidade horrível", "eco", "interferencia", "barulho", "estalo", "chiado", "ruído", "gravação ruim", "gravação péssima", "gravação baixa", "gravação fraca",
          "não deu pra ouvir", "não deu pra escutar", "não entendi nada", "não consegui ouvir direito", "não consegui escutar direito", "não consegui entender", "não consegui compreender", "som ruim", "som péssimo", "som horrível", "som baixo", "som alto", "som travando", "som cortado", "som falhando", "som bugado", "som estranho"
          ],
        
        "Conteúdo diferente da Aula": [
            "não corresponde", "não bate", "não confere", "não combina", "não relacionado", "não pertinente", "não compatível", "não equivalente", "não igual", "não corresponde ao que foi ensinado", "não corresponde ao que foi visto", "não corresponde ao material", "não corresponde à aula",
            "diferente", "divergente", "nao condiz", "outro assunto", "errado", "trocado","conteudo diferente", "conteudo divergente", "conteudo nao condiz", "conteudo outro assunto", "conteudo errado", "conteudo trocado","assunto diferente", "assunto divergente", "assunto nao condiz", "assunto outro assunto", "assunto errado", "assunto trocado","topico diferente", "topico divergente", "topico nao condiz", 
            "topico outro assunto", "topico errado", "topico trocado","não tem nada a ver", "não faz sentido", "não está certo", "não está correto", "não está igual", "não está compatível", "não está relacionado", "não está pertinente", "não está de acordo", "não está alinhado", "não está coerente", "não está consistente",
            "prova diferente da aula", "questão diferente da aula", "atividade diferente da aula", "exercício diferente da aula", "material diferente da aula", "apostila diferente da aula", "slides diferentes da aula"
            
            ],
        
        "Qualidade do Vídeo": [
            "video", "imagem", "resolucao", "baixa qualidade", "pixelado", "borrado", "escuro","qualidade do video", "qualidade da imagem", "resolucao baixa", "video pixelado", "video borrado", "video escuro", "imagem pixelada", "imagem borrada", "imagem escura", "resolucao baixa", "qualidade ruim", "qualidade pessima","qualidade do video", "qualidade da imagem", "resolucao baixa", "video pixelado", "video borrado", "video escuro", "imagem pixelada", "imagem borrada", "imagem escura", "resolucao baixa", "qualidade ruim", 
            "não deu pra ver", "não consegui assistir direito", "não consegui enxergar", "não consegui acompanhar", "não consegui visualizar", "não consegui entender o vídeo", "não consegui entender a imagem", "não consegui ver nada", "não consegui assistir nada", "não consegui enxergar nada", "não consegui acompanhar nada",
            "resolução ruim", "resolução péssima", "resolução horrível", "resolução baixa", "resolução fraca", "resolução limitada", "resolução ruim da imagem", "resolução ruim do vídeo", "qualidade baixa", "qualidade ruim", "qualidade péssima", "qualidade horrível", "qualidade fraca", "qualidade limitada", "qualidade ruim da imagem", "qualidade ruim do vídeo"  
            "qualidade pessima"],
        
        "Edição": [
            "edicao", "corte", "montagem", "transicao", "legenda", 
            "edição ruim", "edição péssima", "edição horrível", "edição fraca", "edição mal feita", "edição mal realizada", "edição mal executada", "edição mal elaborada", "edição mal organizada", "edição mal planejada", "edição mal estruturada", "edição mal montada", "edição mal cortada", "edição mal produzida", "edição mal finalizada", "edição mal concluída",
            "erro de edição", "erro na edição", "erro de corte", "erro na montagem", "erro na transição", "erro na legenda", "edição bugada", "edição estranha", "edição confusa", "edição travada", "edição cortada", "edição falhando", "edição mal explicada", "edição mal apresentada", "edição mal exibida",
            "montagem ruim", "montagem péssima", "montagem horrível", "montagem mal feita", "montagem mal realizada", "montagem mal executada", "montagem mal elaborada", "montagem mal organizada", "montagem mal planejada", "montagem mal estruturada", "montagem mal montada", "montagem mal produzida", "montagem mal finalizada", "montagem mal concluída", "legenda ruim", "legenda péssima", "legenda horrível", "legenda mal feita", "legenda mal realizada", "legenda mal executada", "legenda mal elaborada", "legenda mal organizada", "legenda mal planejada", "legenda mal estruturada", "legenda mal montada", "legenda mal produzida", "legenda mal finalizada", "legenda mal concluída",
            "erro de edicao","edicao ruim", "edicao pessima", "corte ruim", "corte pessimo", "montagem ruim", "montagem pessima", "transicao ruim", "transicao pessima", "legenda ruim", "legenda pessima", "erro de edicao", "erro de edição","erro de edicao", "erro de edição"],
        
        "Musica: Abertura / Fechamento": [
            "musica", "trilha", "abertura", "fechamento", "vinheta", "intro", "volume da musica","musica ruim", "musica pessima", "trilha ruim", "trilha pessima", "abertura ruim", "abertura pessima", "fechamento ruim", "fechamento pessimo", "vinheta ruim", "vinheta pessima", "intro ruim", "intro pessima", "volume da musica ruim", "volume da musica alto", "volume da musica baixo","musica ruim", "musica pessima", "trilha ruim", "trilha pessima", "abertura ruim", "abertura pessima", "fechamento ruim", "fechamento pessimo", "vinheta ruim", "vinheta pessima", "intro ruim", "intro pessima", "volume da musica ruim", "volume da musica alto", "volume da musica baixo",
            "música ruim", "música péssima", "música horrível", "música fraca", "música alta demais", "música baixa demais", "música estranha", "música inadequada", "música fora de contexto", "música fora do tema", "música fora da aula", "música fora da disciplina", "música fora do assunto", "música fora do conteúdo", "música fora da matéria", "música fora da prova", "música fora do exercício", "música fora da atividade",
            "não gostei da música", "não gostei da trilha", "não gostei da abertura", "não gostei do fechamento", "não gostei da vinheta", "não gostei da intro", "música atrapalhou", "trilha atrapalhou", "abertura atrapalhou", "fechamento atrapalhou", "vinheta atrapalhou", "intro atrapalhou", "música incomodou", "trilha incomodou", "abertura incomodou", "fechamento incomodou", "vinheta incomodou", "intro incomodou"
            ],
        
        "Tutor": [
            "tutor", "tutoria", "monitor", "ajuda", "suporte acadêmico", "duvida", "atendimento", "resposta", "rapidez", "eficaz","tutor ruim", "tutor pessimo", "tutoria ruim", "tutoria pessima", "monitor ruim", "monitor pessimo", "ajuda ruim", "ajuda pessima", "suporte academico ruim", "suporte academico pessimo", "duvida sem resposta", "duvida nao respondida", "atendimento ruim", "atendimento pessimo", "resposta ruim", "resposta pessima", "rapidez ruim", "rapidez pessima", "eficaz ruim", "eficaz pessimo","tutor ruim", "tutor pessimo", "tutoria ruim", "tutoria pessima", "monitor ruim", "monitor pessimo", "ajuda ruim", "ajuda pessima", "suporte academico ruim", "suporte academico pessimo", "duvida sem resposta", "duvida nao respondida", "atendimento ruim", "atendimento pessimo", "resposta ruim", "resposta pessima", 
            "orientador", "instrutor", "mentor", "facilitador", "apoio", "suporte", "monitoria", "monitorias", "tutoriais", "assistente", "auxílio", "auxilio", "ajudante", "ajudando", "ajudou", "ajuda rápida", "ajuda lenta", "ajuda eficaz", "ajuda ineficaz",
            "não ajudou", "não explicou", "não respondeu", "não tirou a dúvida", "não deu suporte", "não deu atenção", "não deu retorno", "não deu resposta", "não deu solução", "não resolveu", "não ajudou nada", "não ajudou direito", "não ajudou bem", "não ajudou corretamente", "não ajudou adequadamente", "não ajudou satisfatoriamente", "não ajudou efetivamente", "não ajudou eficientemente", "não ajudou de forma eficaz", "não ajudou de forma eficiente", "ajuda ruim", "ajuda péssima", "ajuda ineficaz", "ajuda lenta", "ajuda demorada", "ajuda insuficiente", "ajuda inadequada", "ajuda insatisfatória", "ajuda ineficiente", "suporte ruim", "suporte péssimo", "suporte ineficaz", "suporte lento", "suporte demorado", "suporte insuficiente", "suporte inadequado", "suporte insatisfatório", "suporte ineficiente",
            "rapidez ruim", "rapidez pessima", "eficaz ruim", "eficaz pessimo"],
        }